image:
  tag: 6.0.1
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik-private
  hosts:
    - grafana.private.k8s.tatooine.thebeat.co
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true
plugins:
  - grafana-piechart-panel
adminPassword: admin
persistence:
  enabled: false
  size: 2Gi
  accessModes:
    - ReadWriteOnce
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
    - name: 'custom'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/custom

sidecar:
  image: kiwigrid/k8s-sidecar:0.0.6
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi
  dashboards:
    enabled: true
    label: grafanaDashboard
    folder: /var/lib/grafana/dashboards/default
    searchNamespace: ALL
  datasources:
    enabled: false
    label: grafanaDatasources
    searchNamespace: null